APP_NAME = hash_table
VERSION = 0.1.2

PACKAGE_CONTENTS := ${SRC_PATH}/${APP_NAME}.h lib${APP_NAME}.a

INSTALL_PATH = /opt
CFLAGS +=

DLINKED_LIST_PROJECT_ID = 18027338
UNITEST_PROJECT_ID = 11728468

STATIC_DEP = dlinked_list
SHARED_DEP =

DEPENDENCIES += gitlab/${DLINKED_LIST_PROJECT_ID}/0.1.0
DEPENDENCIES += gitlab/${UNITEST_PROJECT_ID}/0.2.0

LDFLAGS += ${STATIC_DEP:%=-l%} ${SHARED_DEP:%=-l%}
