name: Test

on:
  push:
     branches: [master]
  pull_request:
      branches: [master]

jobs:
  simple_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt install -y gcc make valgrind
      - name: make test
        run: CFLAGS=-static make test
